### ISSUE TITLE
Add Workday Implementation

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/JWS-Test-Suite#13]
Ping me for assistance.

**Comment by dtmcg** [comment]
suggesting we don't add a Workday implementation. The Workday implemented sig suit is of type JcsEd25519Signature2020 https://identity.foundation/JcsEd25519Signature2020, its similar but not the same. 
I think this may create confusion for an external implementer when looking at the submitted implementations.

**Comment by OR13** [comment]
Closing, workday declined to implement JsonWebSignature2020 or VC-JWT.
