### ISSUE TITLE
Add Aries Framework Go Docker implementation

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/JWS-Test-Suite#4]
Someone from SecureKey please help.

@troyronda please ping the appropriate folks.

**Comment by troyronda** [comment]
@Baha-sk @Moopli ^^^

**Comment by decentralgabe** [comment]
Happy to work with the SecureKey folks on this, it should be fairly similar to our impl https://github.com/decentralized-identity/JWS-Test-Suite/tree/main/implementations/tbd
I don't have the bandwidth to take it on myself

**Comment by Baha-sk** [comment]
we will take it .. hopefully in a couple of weeks we should have a new implementation using Aries Framework Go.
