### ISSUE TITLE
Spruce verify fails on empty files

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/JWS-Test-Suite#40]
there are a couple cases where a vendor fails to produce a VC or a VP.

The the verify logic chokes on attempting to handle this... it should simple return "verification failed" for empty / malformed data.

```
Creating jws-test-suite_spruce_run ... done
Error: Custom { kind: InvalidData, error: Error("missing field `@context`", line: 1, column: 10) }
Error: Failed to verify (1)
    at ChildProcess.<anonymous> (/Users/orie/Desktop/Code/Transmute/JWS-Test-Suite/implementations/spruce/verify.js:21:14)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by wyc** [comment]
cc @clehner

**Comment by peacekeeper** [comment]
I hope we can re-run the [CI workflow](https://github.com/decentralized-identity/JWS-Test-Suite/actions) soon, since the [report](https://identity.foundation/JWS-Test-Suite/#danubetech) is currently showing danubetech failing some tests, which I don't think is true.

**Comment by OR13** [comment]
Looks healed to me:
![Screen Shot 2022-02-01 at 9 42 48 AM](https://user-images.githubusercontent.com/8295856/152000564-4a33da3f-8b13-416a-9759-b38ef93f88d3.png)
