### ISSUE TITLE
[BUG?] `credential-0.json` does not match the VC data model

### ISSUE THREAD

**Issue by mirceanis** [decentralized-identity/JWS-Test-Suite#46]
The VC data model [defines the credentialSubject](https://www.w3.org/TR/vc-data-model/#credential-subject) as : _a set of objects that contain one or more properties that are each related to a subject of the verifiable credential_.

This implies that the credentialSubject property must not be empty, since it has to have one or more properties.

The [credential-0.json](https://github.com/decentralized-identity/JWS-Test-Suite/blob/main/data/credentials/credential-0.json) sample file used in these tests seems to not respect this since it is expecting credentials with empty `credentialSubject` to be valid.

**Comment by kimdhamilton** [comment]
Confirmed that @mirceanis says is still the case in version 1.1 of the spec: https://www.w3.org/TR/2022/REC-vc-data-model-20220303/

**Comment by OR13** [comment]
I think we decided that empty object is a value-able negative test care and that it is not a valid VC, test vectors for happy path testing were updated.
