### ISSUE TITLE
Add support for VC-JWT

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/JWS-Test-Suite#7]
per the work item call today, we agreed to expand scope to enable the ability to demonstrate a VC-JWT capability.

**Comment by OR13** [comment]
I will start this as soon as we have 3 implementations rendering in the report/

**Comment by bumblefudge** [comment]
casually proposed on the call, but not really discussed: separate LDP and VC-JWT sections entirely and repeat all implementations under test for both, for clarity/readability.

**Comment by OR13** [comment]
noting this related issue in ES256K that impacts signatures produced by open SSL.

https://github.com/decentralized-identity/ES256K-interop/issues/1

**Comment by OR13** [comment]
i think we still have some cleanup to do, especially to the report format, before we can call this done.

**Comment by decentralgabe** [comment]
Bumping, we're moving in the right direction but as per the initial issue post seems there's a little bit more work

**Comment by OR13** [comment]
I suggest we close this, and open newer issues for any remaining VC-JWT problems
